@countries  = [ "Argentina",
                "Australia",
                "Austria",
                "Belarus",
                "Belgium",
                "Bosnia and Herzegowina",
                "Brazil",
                "Bulgaria",
                "Canada",
                "Chile",
                "Colombia",
                "Croatia",
                "Czech Republic",
                "Denmark",
                "Ecuador",
                "Estonia",
                "Finland",
                "France",
                "Germany",
                "Greece",
                "Greenland",
                "Hong Kong",
                "Hungary",
                "Iceland",
                "India",
                "Indonesia",
                "Ireland",
                "Israel",
                "Italy",
                "Japan",
                "Latvia",
                "Liechtenstein",
                "Lithuania",
                "Luxembourg",
                "Macedonia, The Former Yugoslav Republic Of",
                "Malta",
                "Mexico",
                "Moldova, Republic of",
                "Monaco",
                "Montenegro",
                "Nepal",
                "Netherlands",
                "New Zealand",
                "Norway",
                "Panama",
                "Papua New Guinea",
                "Paraguay",
                "Peru",
                "Poland",
                "Portugal",
                "Puerto Rico",
                "Romania",
                "Russian Federation",
                "San Marino",
                "Serbia",
                "Slovakia",
                "Slovenia",
                "South Africa",
                "Spain",
                "Sweden",
                "Switzerland",
                "Thailand",
                "Ukraine",
                "United Kingdom",
                "United States",
                "Uruguay",
                "Venezuela",
                "Other"]
