development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: becske2013course@gmail.com
  :password: Lajos1010
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: becske2013course@gmail.com
  :password: Lajos1010
  :enable_starttls_auto: true
test:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: becske2013course@gmail.com
  :password: Lajos1010
  :enable_starttls_auto: true